spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://localhost:8088"
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: employee-group-1
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer