server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/department_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true